### ISSUE TITLE
Add optional box art to detailed view

### ISSUE THREAD

**Issue by tomillr** [20GotoTen/es-theme-retrofix#9]
I'd like to see the option to the corresponding box art in the detailed view:

![Bildschirmfoto 2022-03-07 um 13 17 02](https://user-images.githubusercontent.com/1507977/157033153-f236a8d2-cb04-4401-8479-214827dab5d4.png)

For example, you could display the box art to the left of the current information block. To make room for the box art, the information block could move a bit to the right. It might also help to clean up the look, by changing the text alignment from centered to left.

**Comment by 20GotoTen** [comment]
I think there's something I can do here, leave it with me! Also, V2 has launched.

**Comment by 20GotoTen** [comment]
@tomillr If you're still interested, this has now been implemented!

**Comment by 20GotoTen** [comment]
Thanks for your feedback! The points highlighted are intentional for the time being.

1: The controller icons would have to be re-exported out in a more flexible way. This will require some time.

2: Game genres typically run longer than the example your screenshot shows, I need to get an everage length to determine what that gap should be.

I may revert to the previous genre length to match the others, but I need to rework the metadata display across the whole theme anyway, so chances are it'll happen when that goes into development.

**Comment by tomillr** [comment]
RE point 1:
So you can't just re-use the icon used in the regular "detailed"- in the "detailed boxart"-view?

![Bildschirmfoto 2023-03-27 um 11 26 22](https://user-images.githubusercontent.com/1507977/227901198-634c8583-f153-4f4c-a069-b3a0b6b7bc58.png)

RE point 2:
The empty placeholder space for the longer genre info looks somewhat off to me. Wouldn't it be possible to have the div-container that contains the controller icon and genre text automatically resize to the right depending on the length of the text?

Or as a shortcut re-use the basic layout from the regular "detailed"-view instead? 

![Bildschirmfoto 2023-03-27 um 11 23 18](https://user-images.githubusercontent.com/1507977/227902342-ec40793a-0972-4d79-915f-29cdf4b81aa1.png)
